
title: "Your Name"
description: "Personal site inspired by Kilian Rouge"
author: "Your Name"
baseurl: ""
url: "https://your-github-username.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /blog/:title/

markdown: kramdown
theme: minima
